### ISSUE TITLE
Interested to contribute

### ISSUE THREAD

**Issue by imjafran** [Appsero/client#22]
We have some extended integration with appsero that requires adding some additional hooks for our purposes, like optin/optout, license activation, deactivation and refreshing. 
Also, for manual installation, it conflicts with same library with different project (as the files are loaded more than one time, conflicts the class names). 

Could you please allow me to contribute with a new branch?

**Comment by saiftheboss7** [comment]
HI @imjafran 

Thanks for trying to contribute to the Appsero client. However, our preferred way to accept contributions is via PRs. You can give a PR with the changes you intend to do, and if we like the changes and find out it adds value to our project (and are aligned with our vision), we would be very glad to accept the PR and implement the changes.

You can fork the repo, do the changes and give a detailed reply here on this issue and what you have changed because of X, Y, Z. If everything is fine, we'll gladly accept the PR and make the necessary changes on our end to include your fixes & enhancements.
