### ISSUE TITLE
appsero website - app - does not remove the payment card

### ISSUE THREAD

**Issue by Hakira-Shymuy** [Appsero/client#33]
hello team at WeDevs

look, i have the following situation and I'm really mad at it

last month probably around the middle of the last month, i removed my card from appsero dashboard, to cancel the subscription, as i no longer wish to pay for appsero premium, what is my surprise when today i receive a notification from my bank application, saying that 25 dollars was removed from my card to pay appsero.....

what my surprise that now i go there and i see the card back, the subscription, everything is back there
so my question is, the cancel subscription button is there doing what? a fake button?
did you had a problem on your platform and recovered with a backup? because if so, i got charged by mistake. i canceled the subscription last month, and last week i made sure to go login and check the dashboard to be sure i was at no mistake

is this a joke?

You guys have problem to make your SDK recognize and work in localhost
you guys have problem to make your SDK recognize tracking on the plugin and the stats
basically your SDK does not give any information to the dashboard and people are going blind

and you are not able to have the cards removed from a subscription, when people remove the cards through dashboard
is this sort of a joke?

Im waiting that your website appsero.com comes back online so i can go there and open a support ticket to ask the refund for a product that i wanted no longer to pay, that i removed my card, and no money should had been taken from me
Right now your website is with a 502 bad gateway

Bad gateway Error code 502
Visit [cloudflare.com](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=appsero.com) for more information.
2023-11-04 13:37:18 UTC
You
Browser
Working
Madrid
[Cloudflare](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=appsero.com)
Working
appsero.com
Host
Error

but expect me to contact you as soon as it is online and I'm going to get the 25 dollars back, believe me, otherwise a law suit will fall on you, I'm not joking, I'm starting to get tired of bad service and bad moves on the wordpress plugins and service providers.

**Comment by Hakira-Shymuy** [comment]
ho and another thing, make an email for people when they cancel their subscription
because you send an email when the subscription get paid, you send an email when the subscription is about to get due, but you don't send an email when people cancel their subscription so people don't have a fkin proof of that

another thing that you should do is
when someone cancel the subscription, is to be canceled is not to recover the subscription in a ghost backup recover or whatever your dashboard app is doing there
give an option to remove the card, is really bad that you are saving the card information and i, the card owner, cant ( remove it )
you know that goes against the law in my country right?

**Comment by yeasin1989** [comment]
Hi @Hakira-Shymuy,


I hope that you are having a great day!
I apologize for this inconvenience that happened to you.

**Problem:**
The auto-renewal subscription was active by default. Also, I am requesting a refund for this renewal order.

Guidance:
By default, active auto-renewal subscription charges automatically. Unfortunately, you did not cancel it.
You can easily cancel your auto-renewal subscription anytime from our [support team](https://dashboard.appsero.com/support/create-ticket).
The payment method/card information updates do not change the subscription status.
Next Step:
I want to inform you that, we need a valid email address to verify the identity of a user. Could you make sure that the email is associated with the purchase in order to process an account management ticket?

You can either raise a [ticket](https://dashboard.appsero.com/support/create-ticket) from the Appsero account, or you can share your email address and order number that we can cancel and take as a verification of the user identity. 

I am looking forward to hearing from you.
Have a nice day!

Best Regards,

**Comment by Hakira-Shymuy** [comment]
no im sorry

Do not come with a half template email
i said on the ticket, and I'm going to repeat

i had to cancel the subscription because I'm not planning to use it
anymore, i canceled the subscription around middle of the last month,
before the month ends, last week, i made sure to login on appsero to
certify myself that i indeed canceled subscription to don't have surprises,
and it was canceled, there was the same message ( sorry to see you go ) and
i could not remove my card, so i even checked my bank app if there was a
way to block payments to your service, which have not, i verified 2 times
to be sure that i canceled the service
for my surprise the money got taken from my card, and i do login now and
the subscription is active

I'm not playing around with this situation. the money is needed, i need the
money, i don't want to use appsero, and the money got taken, i cannot
remove the card from my account which is against EU regulations which I'm
going to show you
https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0679
https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex%3A32015L2366
https://gdpr-info.eu/art-15-gdpr/

in Which you ( need to have a way ) for the users to remove their personal
information from your website or application. Bank Account or Cards is
personal information. Right now you are in violation for any EU Citizen.

Look, i know you are just doing your job, i understand that. but i also
know that i was and i am completely sure that i canceled the subscription
last month, and the money got taken from my card anyway
So please, give me back the 25 dollars from November 1, and delete all the
Card information from my Appsero account
There is a date of 5 days for this to be accomplished, which after that i
can and i will take legal action against weDevs

Best regards

**Comment by yeasin1989** [comment]
@Hakira-Shymuy ,

I can understand your situation.

It seems like you missed my previous conversation.
No worries, we can cancel your subscription and process a refund right now.

If you have created a ticket but did not get any reply just share the ticket number.
If not please raise a [ticket](https://dashboard.appsero.com/support/create-ticket) from the Appsero account, or you can share your email address and order number so that we can cancel and take as a verification of the user identity.

I am looking forward to hearing from you.

Best Regards,

**Comment by Hakira-Shymuy** [comment]
@yeasin1989 i would love to share a ticket number but from the appsero dashboard i cant find any ticket number or any reference to the ticket last week and to the ticket today or client number or client id, completely nothing.

billing details are
NUNO FERREIRA
webstudioan@gmail.com

Profile information
First Name - Nuno
Last Name - Ferreira
Email - webstudioan@gmail.com

I have 2 tickets open anyway

**Comment by yeasin1989** [comment]
Hi @Hakira-Shymuy ,

We always care about our client's time/money/effort. As you do not want to continue, without any question we canceled your subscription and refunded the order. The payment gateway may take 5 to 10 working days to deposit to your account.

Next Step:
Please feel free to share if you face any other issues. You are always welcome. :)
Thank you, and have a good day ahead!

Best regards,

**Comment by saiftheboss7** [comment]
We've opted to use Stripe portal from today. This issue should not arise in the future. Closing the issue
